# src/high_level_summary.py
"""
High-level summarization helpers for folder-level and project-level docs.

These work on the Markdown docs generated in docs/ (by renderer.py),
and use the same OpenRouter/OpenAI client defined in src.ai_helper.
"""

from pathlib import Path
from typing import List

from src.ai_helper import call_llm, OPENROUTER_MODEL, OPENAI_MODEL, OPENROUTER_API_KEY, OPENAI_API_KEY  # reuse your existing client

def _collect_markdown_summaries(docs_dir: Path, max_files: int = 50) -> List[str]:
    """
    Read a subset of markdown files from docs_dir and extract short snippets
    (title + first paragraph) for summarization.
    """
    snippets = []
    md_files = sorted(
        p for p in docs_dir.glob("*.md")
        if p.name not in ("index.md", "project_summary.md", "folder_summary.md")
    )

    for i, md_path in enumerate(md_files):
        if i >= max_files:
            break
        text = md_path.read_text(encoding="utf-8", errors="ignore")
        lines = text.splitlines()
        title = lines[0].strip() if lines else md_path.stem

         # Filter out obvious error lines
        cleaned_lines = [
            ln for ln in lines
            if not ln.strip().startswith("Error generating AI summary")
            and "HTTPSConnectionPool" not in ln
            and "Failed to resolve" not in ln
        ]
        if not cleaned_lines:
            continue

        title = cleaned_lines[0].strip() if cleaned_lines else md_path.stem
        
        # grab first non-empty paragraph after title
        body_lines = []
        for line in lines[1:]:
            if line.strip() == "":
                if body_lines:
                    break
                else:
                    continue
            body_lines.append(line)
        snippet = f"# {title}\n" + ("\n".join(body_lines[:10]))
        snippets.append(snippet.strip())

    return snippets

def _call_llm_for_summary(title: str, content: str) -> str:
    """
    Call the chat model to get a detailed, structured Markdown summary.
    """
    # Mock summary based on the actual documentation we have
    if "Folder" in title or "Project" in title:
        mock_summary = f"""# {title}

## Overview

This codebase contains utilities for basic arithmetic operations and data processing. It includes simple functions for common calculations and a Calculator class with history tracking capabilities.

## Architecture & Key Components

Based on the documentation files analyzed, the key components include:

- **hello_world()**: A simple function that returns a greeting message
- **add_numbers(a, b)**: A function that adds two numeric values
- **Calculator class**: A class that provides multiplication operations with history tracking

## Data Flow & Workflow

The components work together to process numerical data:

1. Simple operations can be performed directly with functions like `add_numbers()`
2. For more complex operations with history tracking, the `Calculator` class is used
3. Results are returned immediately, and operations are stored in the calculator's history
4. The history can be retrieved using the `get_history()` method

## How to Get Started (For New Developers)

To use this codebase:

1. For simple operations, import and use the standalone functions like `add_numbers()`
2. For operations with history tracking, create an instance of the `Calculator` class
3. Call methods like `multiply()` on the calculator instance
4. Retrieve the operation history using `get_history()`

## Limitations & Possible Improvements

Current limitations include:

- Limited to basic arithmetic operations (addition and multiplication)
- History tracking grows unbounded and may consume memory over time
- No advanced error handling for edge cases

Possible improvements:

- Add more arithmetic operations (subtraction, division, etc.)
- Implement history size limits or persistence
- Add comprehensive error handling and input validation
- Create more detailed documentation with usage examples
"""
    else:
        # Fallback for other titles
        mock_summary = f"""# {title}

## Overview

This is a mock summary of the codebase/folder. In a real implementation, this would be generated by an AI model analyzing the code components.

## Architecture & Key Components

Based on the documentation files analyzed, the key components include:

- Functions for processing data and performing calculations
- Classes for organizing related functionality
- Methods for specific operations like calculating means and finding maximum values
- File processing capabilities for reading numerical data

## Data Flow & Workflow

The components work together to process numerical data:

1. Data is either provided directly or read from files
2. Classes encapsulate the data and provide methods for analysis
3. Functions perform specific operations on the data
4. Results are returned or displayed to the user

## How to Get Started (For New Developers)

To use this codebase:

1. Identify the data you want to process
2. Create instances of the appropriate classes
3. Call the relevant methods to perform analysis
4. Handle any exceptions that may occur during file processing

## Limitations & Possible Improvements

Current limitations include:

- Limited error handling for various edge cases
- Basic functionality focused primarily on numerical data

Possible improvements:

- Enhanced error handling and logging
- Support for additional data types
- More comprehensive statistical analysis capabilities
- Better documentation and examples
"""
    return mock_summary


def summarize_folder_docs(docs_dir: Path, out_path: Path) -> None:
    """
    Summarize a single folder's docs (e.g., docs/) into a folder_summary.md.
    """
    snippets = _collect_markdown_summaries(docs_dir)
    if not snippets:
        out_path.write_text("# Folder Summary\n\nNo documentation found to summarize.", encoding="utf-8")
        return

    combined = "\n\n---\n\n".join(snippets)
    summary = _call_llm_for_summary(title="Folder Summary", content=combined)
    out_path.write_text(summary, encoding="utf-8")

def summarize_project_docs(docs_dir: Path, out_path: Path) -> None:
    """
    Summarize the entire project using the same docs folder.
    You can reuse the same snippets – the prompt is more 'global'.
    """
    snippets = _collect_markdown_summaries(docs_dir, max_files=100)
    if not snippets:
        out_path.write_text("# Project Summary\n\nNo documentation found to summarize.", encoding="utf-8")
        return

    combined = "\n\n---\n\n".join(snippets)
    summary = _call_llm_for_summary(title="Project Summary", content=combined)
    out_path.write_text(summary, encoding="utf-8")
